# Generated by Django 4.2.6 on 2023-11-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cattle', models.CharField(max_length=35)),
                ('cattleimage', models.CharField(max_length=35)),
                ('cattlecolour', models.CharField(max_length=35)),
            ],
        ),
    ]
