# Generated by Django 4.2.6 on 2023-11-29 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_cattle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cow',
            name='file',
        ),
    ]
